export const chromaCanvasV2Abi = [
  {
    type: "function",
    name: "TIER1_THRESHOLD",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "TIER2_THRESHOLD",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "calculateBurnAP",
    stateMutability: "view",
    inputs: [{ name: "burnTokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "actionPoints",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "applyDiff",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "diffData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getCanvasInfo",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [
      { name: "points", type: "uint256" },
      { name: "diffCount", type: "uint256" },
      { name: "tokenCustomized", type: "bool" },
      { name: "hasPendingCommit", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "submitCommit",
    stateMutability: "nonpayable",
    inputs: [{ name: "commitment", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revealBurnAndApplyDiff",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "burnedTokenId", type: "uint256" },
      { name: "salt", type: "bytes32" },
      { name: "diffData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getBurnCount",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isCustomized",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getPixelsEdited",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "BurnRevealed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "burnedTokenId", type: "uint256" },
      { indexed: true, name: "creditedTokenId", type: "uint256" },
      { indexed: false, name: "actionPointsAwarded", type: "uint256" },
    ],
  },
] as const;
